"""empty message

Revision ID: 04ba1cd318aa
Revises: da515689eb74
Create Date: 2023-03-07 10:48:44.227336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ba1cd318aa'
down_revision = 'da515689eb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.Integer(), nullable=True))
        batch_op.drop_column('usertype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usertype', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
