"""empty message

Revision ID: 558bd06e3cf4
Revises: f40c031ccee8
Create Date: 2023-03-28 02:36:16.597664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558bd06e3cf4'
down_revision = 'f40c031ccee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_name', sa.String(length=80), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('subject_name')

    # ### end Alembic commands ###
